services:
  - type: web
    name: sqfx-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

  - type: worker
    name: sqfx-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    plan: free
